# Generated by Django 2.1.15 on 2024-04-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dance_info', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
