# Generated by Django 4.2.11 on 2024-04-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0002_alter_dance_id_usercontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserContent',
        ),
    ]
